### PR TITLE
Allow using Haml 6.0 and drop 5.x and earlier

### LINKED ISSUE #80: haml 6 support
middlean-syntax 3.3.0 does not support for haml 6.0.0.beta.2.

A combination of haml 6.0.0.beta.2 and middlean-syntax 3.3.0 causes errors on `middleman build` (maybe `middleman server` as wel).

## Why

https://github.com/middleman/middleman-syntax/blob/d1b3edd4d2a5ad1028621f6c03ab709a1d94d4e2/lib/middleman-syntax/haml_monkey_patch.rb#L1-L6

does not support haml 6 classes.

## Workaround

```diff
$ git diff lib/middleman-syntax/haml_monkey_patch.rb
--- a/vendor/bundle/ruby/3.1.0/gems/middleman-syntax-3.3.0/lib/middleman-syntax/haml_monkey_patch.rb 2022-08-31 00:00:00.123456789 +0000
+++ b/vendor/bundle/ruby/3.1.0/gems/middleman-syntax-3.3.0/lib/middleman-syntax/haml_monkey_patch.rb 2022-08-31 00:00:00.123456789 +0000
@@ -1,8 +1,9 @@
 # If Haml is around, define a :code filter that can be used to more conveniently output highlighted code.
 if defined? Haml
   module Haml
-    class Filters
-      class Code < Base
+    module Filters
+      module Code
+        include Base
 
         def render(code)
           code = code.rstrip
```

### PR DESCRIPTION
**Pull request by tnir**
Closes #80

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

### CODE REVIEW

**Comment by k0kubun** [comment]
You might be interested in this discussion: https://github.com/haml/haml/issues/1089

**Comment by bostonaholic** [comment]
Any updates on when this can get merged? `middleman-syntax 3.3.0` still does not support `haml 6.x.x`.

**Comment by markets** [comment]
@tdreyno could you please merge and release this one 🙏🏼? Since MM v4.5.0 (https://github.com/middleman/middleman/blob/main/CHANGELOG.md#450) Haml 6 is already supported by MM, but incompatible with this plugin.

**Comment by tdreyno** [comment]
Can we do this without dropping support for Haml 5? I'd prefer not to have a breaking change.

**Comment by markets** [comment]
That makes sense! @tnir could you please update your patch 🙏🏼?

**Comment by markets** [comment]
@tnir @tdreyno just in case, proposed a new PR here 👉🏼 https://github.com/middleman/middleman-syntax/pull/82

**Pull request closed without merging**
