### PR TITLE
Upgrade to Rouge 2.0

### PR DESCRIPTION
**Pull request by di**
This PR upgrades to Rouge 2.0 which was released on June 14th.

See https://github.com/jneen/rouge#formatters for more information.

### CODE REVIEW

**Comment by bhollis** [comment]
Neat. How's the compatibility of this vs. the old one?

**Comment by lwr** [comment]
I really need these upgrades
- javascript - lack of ES6 string support
- javascript - switch case statements marked as errors: <https://github.com/jneen/rouge/issues/497>

**Comment by di** [comment]
@bhollis I believe the only difference is that due to https://github.com/jneen/rouge/commit/f287925ad4ab0ca161d46d6df2ec3c0954772c3e, the CSS class names `gutter`, `table` and `code` are now prefixed with `rouge-` by default.

Plus, lots of bugfixes.

**Comment by bhollis** [comment]
Released middleman-syntax 3.0.0

**Pull request merged**
